# Use as is if using self-managed Temporal cluster deployed alongside Retool
# Compare other deployment options here: https://docs.retool.com/self-hosted/concepts/temporal#compare-options
services:
  order-app-db:
    image: postgres:15
    container_name: order_db
    env_file: ./backend/order-app.env
    volumes:
      - order-app-data:/var/lib/postgresql/data
    networks:
      - private-order-app-network

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.order_mgmt
    env_file: ./backend/order-app.env
    container_name: order-app
    volumes:
      - ./backend:/app # this mounts your source code
    working_dir: /app
    depends_on:
      - order-app-db
    ports:
      - "8000:8000"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    networks:
      - frontend-network
      - private-order-app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend-container
    ports:
      - "80:80"
    networks:
      - frontend-network


networks:
  frontend-network:
  private-order-app-network:

volumes:
  order-app-data:
