services:
  orders-db:
    image: postgres:15
    container_name: orders-db
    env_file: ./backend/order-app.env
    volumes:
      - order-app-data:/var/lib/postgresql/data
    networks:
      - private-order-app-network

  orders-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.order_mgmt
    env_file: ./backend/order-app.env
    container_name: orders-backend
    volumes:
      - ./backend:/app
    working_dir: /app
    depends_on:
      - orders-db
    expose:
      - "8000"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    networks:
      - app-network
      - private-order-app-network

  orders-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: orders-frontend
    expose:
      - "80"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - orders-frontend
      - orders-backend
    networks:
      - app-network

networks:
  app-network:
  private-order-app-network:

volumes:
  order-app-data:
