"""add is deleted flag to product

Revision ID: accfee0107b6
Revises: bca7649f4475
Create Date: 2025-05-03 17:23:29.892720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accfee0107b6'
down_revision: Union[str, None] = 'bca7649f4475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.execute("""
    UPDATE products
    SET deleted = false
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted')
    # ### end Alembic commands ###
