"""remove Foreign Key constrain from product id

Revision ID: bca7649f4475
Revises: e65a8697fbc9
Create Date: 2025-05-03 17:21:50.989866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca7649f4475'
down_revision: Union[str, None] = 'e65a8697fbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_product_id_fkey', 'order_items', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('order_items_product_id_fkey', 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
